### PR TITLE
[GSOC 2019] Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L nto,vertexes -S *.svg`

### CODE REVIEW

**Comment by luzpaz** [comment]
CC @SurajDadral

**Comment by luzpaz** [comment]
Hi @amrit3701 I was confused by the method this PR was merged. It seems to have merged gsoc19 in to this PR instead of the opposite and then it was merged in to master. So I get inconsistencies in the gsoc2019. So do I just send PRs to master then ?

**Comment by luzpaz** [comment]
I'm actually concerned that some files didn't get merged in to master correctly ? example `ColumnReinforcement/SingleTieMultipleRebars.py`

**Comment by amrit3701** [comment]
> Hi @amrit3701 I was confused by the method this PR was merged. It seems to have merged the `gsoc19` branch in to this PR branch `gsoc19-typos` instead of the opposite and then it was merged in to master. So I get inconsistencies in the `gsoc219` branch now.
> 
> So do I just send PRs to master then ?

Hi @luzpaz 

No, need to create another PR to master branch. This week I will merge `gsoc19` branch to `master` branch. Actually, I am waiting for Suraj response (currently he is testing his work with different inputs). When he shows me the green light then I will merge his work to `master`.

Thanks,

**Pull request merged**
